import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

type HttpMethod = 'get' | 'post' | 'put' | 'patch' | 'delete';

interface OpenApiDocument {
	paths?: Record<string, Record<string, OpenApiOperation | undefined> | undefined>;
}

interface OpenApiOperation {
	operationId?: string;
	parameters?: Array<{ name?: string; in?: string; required?: boolean }>;
	requestBody?: unknown;
}

interface Operation {
	method: HttpMethod;
	operationId: string;
	dataType: string;
	responsesType: string;
	hasBody: boolean;
	hasQuery: boolean;
	queryRequired: boolean;
	pathParams: string[];
}

interface TreeNode {
	name: string;
	staticChildren: Map<string, TreeNode>;
	paramChild?: { paramName: string; node: TreeNode };
	operations: Map<HttpMethod, Operation>;
}

const methods = new Set<HttpMethod>(['get', 'post', 'put', 'patch', 'delete']);
const inputPath = resolve('openapi.json');
const outputPath = resolve('src/generated/resource-client.gen.ts');
const document = JSON.parse(readFileSync(inputPath, 'utf8')) as OpenApiDocument;
const root = createNode('root');
const operations: Operation[] = [];

for (const [path, pathItem] of Object.entries(document.paths ?? {})) {
	if (!pathItem) continue;
	for (const [method, operation] of Object.entries(pathItem)) {
		if (!methods.has(method as HttpMethod) || !operation?.operationId) continue;
		addOperation(path, method as HttpMethod, operation);
	}
}

writeGeneratedFile();

function addOperation(path: string, method: HttpMethod, openApiOperation: OpenApiOperation): void {
	const pathWithoutApiPrefix = path.replace(/^\/api(?:\/|$)/, '/');
	const segments = pathWithoutApiPrefix.split('/').filter(Boolean);
	let node = root;
	const pathParams: string[] = [];

	for (const segment of segments) {
		const paramName = getPathParamName(segment);
		if (paramName) {
			pathParams.push(paramName);
			if (!node.paramChild) {
				node.paramChild = { paramName, node: createNode(paramName) };
			}
			node = node.paramChild.node;
			continue;
		}

		const property = toCamelCase(segment);
		let child = node.staticChildren.get(property);
		if (!child) {
			child = createNode(property);
			node.staticChildren.set(property, child);
		}
		node = child;
	}

	const operationId = openApiOperation.operationId;
	const operation: Operation = {
		method,
		operationId,
		dataType: `${upperFirst(operationId)}Data`,
		responsesType: `${upperFirst(operationId)}Responses`,
		hasBody: openApiOperation.requestBody !== undefined,
		hasQuery: (openApiOperation.parameters ?? []).some(parameter => parameter.in === 'query'),
		queryRequired: (openApiOperation.parameters ?? []).some(parameter => parameter.in === 'query' && parameter.required === true),
		pathParams
	};

	node.operations.set(method, operation);
	operations.push(operation);
}

function writeGeneratedFile(): void {
	const interfaces = new Map<TreeNode, string>();
	assignInterfaceNames(root, [], interfaces);

	const importedTypes = Array.from(
		new Set(operations.flatMap(operation => [operation.responsesType, ...(operation.hasBody || operation.hasQuery ? [operation.dataType] : [])]))
	).sort();
	const chunks: string[] = [
		'// This file is auto-generated by packages/api-client/scripts/generate-resource-client.ts',
		'',
		"import { apiResult, type KubwaveApiResult, type NormalizeApiData } from '../runtime/result.js';",
		"import type * as sdk from './sdk.gen.js';",
		'import type {',
		...importedTypes.map(typeName => `\t${typeName},`),
		"} from './types.gen.js';",
		'',
		'type SdkModule = typeof sdk;',
		'type SdkFunctionName = {',
		'\t[K in keyof SdkModule]: SdkModule[K] extends (...args: infer _TArgs) => unknown ? K : never;',
		'}[keyof SdkModule];',
		'',
		'type BoundOptions<T> = T extends (options: infer TOptions) => unknown',
		"\t? Omit<TOptions, 'client'>",
		'\t: T extends (options?: infer TOptions) => unknown',
		"\t\t? Omit<NonNullable<TOptions>, 'client'>",
		'\t\t: never;',
		'',
		'type BoundFunction<T> = T extends (options: infer TOptions) => infer TResult',
		'\t? undefined extends TOptions',
		'\t\t? (options?: BoundOptions<T>) => TResult',
		'\t\t: (options: BoundOptions<T>) => TResult',
		'\t: never;',
		'',
		'export type KubwaveRawClient = {',
		'\t[K in SdkFunctionName]: BoundFunction<SdkModule[K]>;',
		'};',
		'',
		'type ResponseData<TResponses> = NormalizeApiData<TResponses[keyof TResponses]>;',
		'type OperationResult<TResponses> = Promise<KubwaveApiResult<ResponseData<TResponses>>>;',
		''
	];

	for (const [node, interfaceName] of interfaces) {
		chunks.push(renderInterface(node, interfaceName, interfaces), '');
	}

	chunks.push('export function createResourceClient(raw: KubwaveRawClient): KubwaveResourceClient {');
	chunks.push(`\treturn ${renderNodeValue(root, 'raw', [])} as KubwaveResourceClient;`);
	chunks.push('}');
	chunks.push('');

	mkdirSync(dirname(outputPath), { recursive: true });
	writeFileSync(outputPath, `${chunks.join('\n')}\n`);
}

function renderInterface(node: TreeNode, interfaceName: string, interfaces: Map<TreeNode, string>): string {
	const lines = [`export type ${interfaceName} = {`];

	if (node === root) {
		lines.push('\traw: KubwaveRawClient;');
	}

	if (node.paramChild) {
		const childInterface = interfaces.get(node.paramChild.node);
		if (!childInterface) throw new Error(`Missing interface for ${node.paramChild.paramName}`);
		lines.push(`\t(${node.paramChild.paramName}: string): ${childInterface};`);
	}

	for (const [method, operation] of sortedOperations(node)) {
		lines.push(`\t${method}(${renderMethodArgs(operation)}): OperationResult<${operation.responsesType}>;`);
	}

	for (const [property, child] of sortedStaticChildren(node)) {
		const childInterface = interfaces.get(child);
		if (!childInterface) throw new Error(`Missing interface for ${property}`);
		lines.push(`\t${property}: ${childInterface};`);
	}

	lines.push('};');
	return lines.join('\n');
}

function renderNodeValue(node: TreeNode, rawName: string, params: string[]): string {
	const entries: string[] = [];
	if (node === root) entries.push(`raw: ${rawName}`);

	for (const [method, operation] of sortedOperations(node)) {
		entries.push(
			`${method}: (${renderMethodArgs(operation)}) => apiResult(${rawName}.${operation.operationId}(${renderOperationOptions(operation, params)}))`
		);
	}

	for (const [property, child] of sortedStaticChildren(node)) {
		entries.push(`${property}: ${renderNodeValue(child, rawName, params)}`);
	}

	const objectValue = entries.length > 0 ? `{\n${entries.map(entry => `\t${entry}`).join(',\n')}\n}` : '{}';
	if (!node.paramChild) return objectValue;

	const childParams = [...params, node.paramChild.paramName];
	return `Object.assign((${node.paramChild.paramName}: string) => (${renderNodeValue(node.paramChild.node, rawName, childParams)}), ${objectValue})`;
}

function renderMethodArgs(operation: Operation): string {
	const args: string[] = [];
	if (operation.hasBody) args.push(`body: ${operation.dataType}['body']`);
	if (operation.hasQuery) args.push(`query${operation.queryRequired ? '' : '?'}: ${operation.dataType}['query']`);
	return args.join(', ');
}

function renderOperationOptions(operation: Operation, availableParams: string[]): string {
	const entries: string[] = [];
	const paramEntries = operation.pathParams.filter(param => availableParams.includes(param)).map(param => `${param}: ${param}`);
	if (paramEntries.length > 0) entries.push(`path: { ${paramEntries.join(', ')} }`);
	if (operation.hasBody) entries.push('body');
	if (operation.hasQuery) entries.push('query');
	return entries.length > 0 ? `{ ${entries.join(', ')} }` : '{}';
}

function assignInterfaceNames(node: TreeNode, parts: string[], interfaces: Map<TreeNode, string>): void {
	const interfaceName = node === root ? 'KubwaveResourceClient' : `Kubwave${parts.map(upperFirst).join('')}Resource`;
	interfaces.set(node, interfaceName);

	if (node.paramChild) {
		assignInterfaceNames(node.paramChild.node, [...parts, upperFirst(node.paramChild.paramName)], interfaces);
	}

	for (const [property, child] of sortedStaticChildren(node)) {
		assignInterfaceNames(child, [...parts, property], interfaces);
	}
}

function sortedStaticChildren(node: TreeNode): Array<[string, TreeNode]> {
	return Array.from(node.staticChildren.entries()).sort(([left], [right]) => left.localeCompare(right));
}

function sortedOperations(node: TreeNode): Array<[HttpMethod, Operation]> {
	const order: HttpMethod[] = ['get', 'post', 'put', 'patch', 'delete'];
	return order.flatMap(method => {
		const operation = node.operations.get(method);
		return operation ? [[method, operation] as [HttpMethod, Operation]] : [];
	});
}

function createNode(name: string): TreeNode {
	return { name, staticChildren: new Map(), operations: new Map() };
}

function getPathParamName(segment: string): string | null {
	const match = /^\{(?<name>[^}]+)\}$/.exec(segment);
	return match?.groups?.name ?? null;
}

function toCamelCase(value: string): string {
	return value.replace(/[-_]+([a-zA-Z0-9])/g, (_match, letter: string) => letter.toUpperCase());
}

function upperFirst(value: string): string {
	return `${value.charAt(0).toUpperCase()}${value.slice(1)}`;
}
