// Shared vue-query key factory so queries and invalidations line up across the app.
export const queryKeys = {
	teams: ['teams'] as const,
	teamMembers: (teamId: string) => ['teams', teamId, 'members'] as const,
	teamSshKeys: (teamId: string) => ['teams', teamId, 'ssh-keys'] as const,
	teamProjects: (teamId: string) => ['teams', teamId, 'projects'] as const,
	project: (projectId: string) => ['projects', projectId] as const,
	services: ['services'] as const,
	environments: ['environments'] as const,
	environmentServices: (environmentId: string) => ['environments', environmentId, 'services'] as const,
	environmentFlowLayout: (environmentId: string) => ['environments', environmentId, 'flow-layout'] as const,
	environmentServiceStatus: (environmentId: string) => ['environments', environmentId, 'services', 'status'] as const,
	templates: ['templates'] as const,
	service: (serviceId: string) => ['services', serviceId] as const,
	serviceStatus: (serviceId: string) => ['services', serviceId, 'status'] as const,
	serviceConnection: (serviceId: string) => ['services', serviceId, 'connection'] as const,
	serviceMetrics: (serviceId: string, range: string) => ['services', serviceId, 'metrics', range] as const,
	serviceLogs: (serviceId: string, pod: string, tailLines: number) => ['services', serviceId, 'logs', pod, tailLines] as const,
	serviceDeployments: (serviceId: string) => ['services', serviceId, 'deployments'] as const,
	deployment: (deploymentId: string) => ['deployments', deploymentId] as const,
	deploymentLogs: (deploymentId: string) => ['deployments', deploymentId, 'logs'] as const,
	deploymentBuildLogs: (deploymentId: string) => ['deployments', deploymentId, 'build-logs'] as const,
	health: ['admin', 'health'] as const,
	invitations: ['invitations'] as const,
	adminUsers: ['admin', 'users'] as const,
	smtp: ['admin', 'smtp'] as const,
	metricsSettings: ['admin', 'metrics'] as const,
	haSettings: ['admin', 'ha'] as const,
	volumeAutoscalingSettings: ['admin', 'volume-autoscaling'] as const,
	platformVolumes: ['admin', 'platform-volumes'] as const,
	deploymentConcurrency: ['admin', 'deployment-concurrency'] as const,
	prPreviews: ['admin', 'pr-previews'] as const,
	defaultDomain: ['admin', 'domain'] as const,
	registrySettings: ['admin', 'registry'] as const,
	version: ['admin', 'version'] as const,
	updates: ['admin', 'updates'] as const,
	updateRun: (runId: string) => ['admin', 'updates', runId] as const,
	updateRunLogs: (runId: string) => ['admin', 'updates', runId, 'logs'] as const
};
