{{- if and .Values.api.secret.create (not .Values.api.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.secret.name }}
  labels:
    {{- include "kubwave.labels" (dict "root" $ "component" "api") | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  {{- range $k, $v := .Values.api.secret.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
