{{- if .Values.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.api.serviceAccount.name }}
  labels:
    {{- include "kubwave.labels" (dict "root" $ "component" "api") | nindent 4 }}
{{- end }}
