{{- if .Values.update.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.update.serviceAccount.name }}
  labels:
    {{- include "kubwave.labels" (dict "root" $ "component" "updater") | nindent 4 }}
{{- end }}
