import { describe, expect, test } from 'bun:test';
import sshpk from 'sshpk';
import { generateSshKeyPair, isSupportedSshKeyType, parseSshPrivateKey, SshKeyEncryptedError, SshKeyParseError } from '../src/index';

describe('generateSshKeyPair', () => {
	test('generates an ed25519 keypair', () => {
		const key = generateSshKeyPair();
		expect(key.keyType).toBe('ed25519');
	});

	test('public key is a comment-free OpenSSH line', () => {
		const { publicKey } = generateSshKeyPair();
		expect(publicKey.startsWith('ssh-ed25519 ')).toBe(true);
		// exactly "<type> <base64>" — no trailing comment field
		expect(publicKey.split(' ')).toHaveLength(2);
	});

	test('fingerprint is a SHA256 fingerprint string', () => {
		const { fingerprint } = generateSshKeyPair();
		expect(fingerprint.startsWith('SHA256:')).toBe(true);
	});

	test('private key is usable OpenSSH format whose public half matches', () => {
		const { privateKey, publicKey } = generateSshKeyPair();
		expect(privateKey).toContain('BEGIN OPENSSH PRIVATE KEY');
		const reparsed = sshpk.parsePrivateKey(privateKey, 'auto');
		const reparsedPub = reparsed.toPublic().toString('ssh').split(' ').slice(0, 2).join(' ');
		expect(reparsedPub).toBe(publicKey);
	});

	test('each call produces a distinct key', () => {
		expect(generateSshKeyPair().publicKey).not.toBe(generateSshKeyPair().publicKey);
	});
});

describe('parseSshPrivateKey', () => {
	test('accepts a generated ed25519 key and derives the matching public key', () => {
		const generated = generateSshKeyPair();
		const parsed = parseSshPrivateKey(generated.privateKey);
		expect(parsed.keyType).toBe('ed25519');
		expect(parsed.publicKey).toBe(generated.publicKey);
		expect(parsed.fingerprint).toBe(generated.fingerprint);
	});

	test('normalizes the stored private key to OpenSSH format', () => {
		const generated = generateSshKeyPair();
		const parsed = parseSshPrivateKey(generated.privateKey);
		expect(parsed.privateKey).toContain('BEGIN OPENSSH PRIVATE KEY');
	});

	test('accepts an uploaded RSA private key and reports its type', () => {
		// RSA can't be generated by sshpk; build one via node:crypto and feed it as an upload.
		const pem = sshpk.parsePrivateKey(rsaPkcs8Pem(), 'auto').toString('openssh');
		const parsed = parseSshPrivateKey(pem);
		expect(parsed.keyType).toBe('rsa');
		expect(parsed.publicKey.startsWith('ssh-rsa ')).toBe(true);
	});

	test('rejects garbage input with SshKeyParseError', () => {
		expect(() => parseSshPrivateKey('not a key')).toThrow(SshKeyParseError);
	});

	test('rejects a passphrase-protected key with SshKeyEncryptedError', () => {
		const encrypted = sshpk.generatePrivateKey('ed25519').toString('openssh', { passphrase: 'hunter2' });
		expect(() => parseSshPrivateKey(encrypted)).toThrow(SshKeyEncryptedError);
	});

	test('rejects a public key pasted where a private key is expected', () => {
		const publicLine = generateSshKeyPair().publicKey;
		expect(() => parseSshPrivateKey(publicLine)).toThrow(SshKeyParseError);
	});
});

describe('isSupportedSshKeyType', () => {
	test('accepts ed25519, rsa and ecdsa', () => {
		expect(isSupportedSshKeyType('ed25519')).toBe(true);
		expect(isSupportedSshKeyType('rsa')).toBe(true);
		expect(isSupportedSshKeyType('ecdsa')).toBe(true);
	});

	test('rejects legacy/unknown types', () => {
		expect(isSupportedSshKeyType('dsa')).toBe(false);
		expect(isSupportedSshKeyType('')).toBe(false);
	});
});

function rsaPkcs8Pem(): string {
	const { generateKeyPairSync } = require('node:crypto');
	const { privateKey } = generateKeyPairSync('rsa', {
		modulusLength: 2048,
		privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
		publicKeyEncoding: { type: 'spki', format: 'pem' }
	});
	return privateKey;
}
