{{- if and .Values.postgres.secret.create (not .Values.postgres.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secret.name }}
  labels:
    {{- include "kubwave.labels" (dict "root" $ "component" "postgres") | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  {{- range $k, $v := .Values.postgres.secret.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
