#!/usr/bin/env bash
# Regenerate the embedded GCP PD CSI driver manifest from the upstream stable-master overlay.
#
# We pin a COMMIT SHA, not a release tag. The stable-master overlay tracks master HEAD, where the
# driver image pin and the controller args stay in sync. A release TAG's stable-master can be
# internally stale (e.g. v1.26.0 still pinned the old v1.17.4 image while args already used newer
# flags like --enable-multitenancy → the driver crashlooped on "flag provided but not defined").
# Pin a SHA where image and args are consistent; a SHA is also immutable (a moved tag can't change
# what regen produces).
#
# To bump: pick a newer master commit where stable-master is consistent, set OVERLAY_SHA + DRIVER_VERSION
# below (keep DRIVER_VERSION in sync with GCP_PD_CSI_VERSION in csi-catalog.ts), re-run, and review the diff.
set -euo pipefail

# Driver image version shipped by the pinned overlay (for humans / the catalog constant).
DRIVER_VERSION="v1.26.0"
# Upstream commit to render from. Defaults to a master commit verified consistent (image v1.26.0 + matching args).
OVERLAY_SHA="${1:-d947b3b43676317a8786a58b784d61f8998943a1}"
OUT="apps/cli/src/platforms/cloudfleet/gcp/pd-csi-driver.yaml"
OVERLAY="github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/deploy/kubernetes/overlays/stable-master?ref=${OVERLAY_SHA}"

echo "# Generated by scripts/gen-gcp-csi-manifest.sh — do not edit by hand." > "$OUT"
echo "# Driver ${DRIVER_VERSION}, rendered from pinned commit ${OVERLAY_SHA}." >> "$OUT"
echo "# Source: ${OVERLAY}" >> "$OUT"
# The upstream overlay assumes the namespace pre-exists; prepend it so the manifest is self-contained.
cat >> "$OUT" <<'NS'
apiVersion: v1
kind: Namespace
metadata:
  name: gce-pd-csi-driver
---
NS
kubectl kustomize "$OVERLAY" >> "$OUT"
echo "Wrote $OUT ($(grep -c '^kind:' "$OUT") objects) — driver ${DRIVER_VERSION} @ ${OVERLAY_SHA}"
